import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { Toaster } from 'sonner';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Navbar />
        <div className="container">
                  {children}
          <Toaster richColors position="top-right" />
        </div>
      </body>
    </html>
  );
}


